---
nfs_server: true
spec_nfs_gr1: "Специальная_группа"

nfs_users:
  user3:
    name: "samba_u3"
    password: "1qaz@WSX"
    given_name: 'Колкин Павел Сергеевич'
    mail: 'garaj@den.skv'
  user4:
    name: "samba_u4"
    password: "1qaz@WSX"
    given_name: 'Николай Сергеевич Мячиков'
    mail: 'djin_udachi@den.skv'

nfs_shares:
  root:
    path: "/srv/smb"
  trash:
    path: "/srv/smb/trash"
  NOTadmins:
    path: "/srv/smb/NOTadmins"
  work:
    path: "/srv/smb/work"
  spec_GR1:
    path: "/srv/smb/spec_GR1"
main_nfs_options: "rw,no_subtree_check"
secure_nfs_options: ",sec=krb5:krb5i:krb5p"
...
