---
- name: Обновление кеша пакетов
  apt_rpm:
    update_cache: true
  when: dist_upd | bool

- name: Установка базовых пакетов при вводе в домен
  apt_rpm:
    name: "{{ base_pkg }}"
    state: installed
  when:
    - dist_upd | bool

- name: Обновление пакетов
  apt_rpm:
    dist_upgrade: true
  when: dist_upgrd | bool

- name: Обновление ядра
  apt_rpm:
    update_kernel: true
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/sbin"
  ignore_errors: true
  when: kernel_upd | bool

- name: Установка имени хоста
  hostname:
    name: "{{ ansible_hostname ~'.'~ ad_workgroup }}"

- name: Определить основной интерфейс
  set_fact:
    primary_iface_name: >-
      {{
          ansible_interfaces
          | difference(['lo'])
          | select('match', '^(eth|en)[a-z0-9]*')
          | first
      }}
  when:
    - ( ansible_default_ipv4.address.split('.')[3] | int ) < 50

- name: Настройка DNS резолвера
  template:
    src: resolv.conf.j2
    dest: "/etc/net/ifaces/{{ primary_iface_name }}/resolv.conf"
  when:
    - ( ansible_default_ipv4.address.split('.')[3] | int ) < 50

- name: Отключение IPv6 прописываем конфиг
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: true
  
- name: Отключение IPv6 применение конфига
  command: /sbin/sysctl -p

- name: Создание службы применения sysctl после загрузки
  copy:
    src: apply-sysctl.service
    dest: /etc/systemd/system/apply-sysctl.service
    mode: '0755'

- name: Включить сервис apply-sysctl
  systemd:
    name: apply-sysctl
    enabled: true
    masked: false
    daemon_reload: true

- name: Настройка chrony.conf для пользователей домена
  template:
    src: chrony.conf.members.j2
    dest: /etc/chrony.conf
    backup: true
  when:
    - ( ansible_default_ipv4.address.split('.')[3] | int ) < 50

- name: Запуск и включение службы chronyd
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    masked: false
    daemon_reload: true
  loop:
    - chronyd

- name: Перезагрузка после обновлений
  reboot:
    reboot_timeout: 240
...
