#!/usr/bin/env ansible-playbook
---
- name: DHCP с failover и DDNS
  hosts: domain_controllers:file_servers:proxy_servers
  become: true
  become_method: su
  become_user: root
  roles:
    - dhcp_server
...
