#!/usr/bin/env ansible-playbook
---
- name: Samba Active Directory DC
  hosts: domain_controllers
  become: true
  become_method: su
  become_user: root
  gather_facts: true
  roles:
    - samba_ad_dc
...
