#!/usr/bin/env ansible-playbook
---
- name: Smb файловый сервер
  hosts: [file_servers, domain_controllers]
  become: true
  become_method: su
  become_user: root
  gather_facts: true
  roles:
    - smb_shares
...
