#!/usr/bin/env ansible-playbook
---
- name: Фильтрация доступных clients
  hosts: altwks1
  become: false
  gather_facts: true
  tasks:
    - name: Доступность хостов из группы clients
      shell: |
        nmap -sn "{{ item }}" | grep 'Nmap scan report for' | awk '{print $5}'
      register: ping_results
      with_inventory_hostnames:
        - clients
      ignore_errors: true

    - name: Добавление в динамическую группу доступных хостов
      add_host:
        name: "{{ item.item }}"
        groups: reachable_clients
      loop: "{{ ping_results.results }}"
      when: >
        item.rc == 0
        and item.stdout.strip() != ""
        and "Failed to resolve" not in item.stderr

- name: Тестирование инфраструктуры
  hosts: all:!clients,reachable_clients
  gather_facts: true
  become: true
  become_method: su
  become_user: root
  roles:
    - tests_vkr
...
