---
#====| Общие параметры |===#
# параметры суперпользователя
ansible_ssh_private_key_file: "~/.ssh/id_skv_VKR_vpn"
ansible_python_interpreter: "/usr/bin/python3"

# параметры домена
ad_workgroup: "den.skv"
ad_realm: "DEN.SKV"
ad_domain: "DEN"
ad_admin_user: "Administrator"
dns_forwarder: "77.88.8.8"
# Хост имена и ip контроллеров домена
primary_dc: "{{ groups['domain_controllers'][0] }}"
primary_dc_ip: "{{ hostvars[primary_dc]['ansible_host'] }}"
secondary_dc: "{{ groups['domain_controllers'][1] }}"
secondary_dc_ip: "{{ hostvars[secondary_dc]['ansible_host'] }}"

#====| ВКЛ\ВЫКЛ ролей |===#

# включаем(true)\выключаем(false) РОЛИ
base_setup: true

chrony_sync: true

sysvol_replication: true  # на эту переменную завязаны репликации служб AD и DHCP
samba_ad_dc: true
dhcp_server: true

smb_shares: true
nfs_server: true

squid_proxy: true

tests_vkr: true

#====| Переназначенные параметры ролей |===#

# ==| Для роли Базовой настройки |== #
dist_upd: true # Обновление кеша пакетов
dist_upgrd: true # обновление установленных приложений
kernel_upd: true # обновление ядра

# ==| Для роли chrony |== #
exter_ntp: ntp3.vniiftri.ru
allow_clients: "192.168.100.0/24"

# ==| Для роли AD |== #
ad_backend: 'SAMBA_INTERNAL'
dns_refresh: 720
ptr_zone: "100.168.192.in-addr.arpa"
ptr_ip_main_dc: 12
ptr_ip_second_dc: 13
ldap_search: "dc=den,dc=skv"

# ==| Для роли DHCP |== #
network_subnet: "192.168.100.0"
network_netmask: "255.255.255.0"
network_gateway: "192.168.100.1"
broadcast: "192.168.100.255"
dhcp_range: "192.168.100.50 192.168.100.254"

# ==| Для sysvol репликации |== #
ssh_sysvol_path: "/root/.ssh/id_sysvol_ed25519"
synchron_path: "/var/lib/samba/sysvol"

# ==| Для роли SMB сервера |== #
spec_smb_gr1: "Специальная_группа"

samba_users:
  user1:
    name: "samba_u1"
    password: "1qaz@WSX"
    given_name: 'Василий Иванович Чапаев'
    mail: 'chapay_vi@den.skv'
  user2:
    name: "samba_u2"
    password: "1qaz@WSX"
    given_name: 'Моледцев Владимир Александрович'
    mail: 'syn_polka@den.skv'
  user3:
    name: "samba_u3"
    password: "1qaz@WSX"
    given_name: 'Колкин Павел Сергеевич'
    mail: 'garaj@den.skv'
  user4:
    name: "samba_u4"
    password: "1qaz@WSX"
    given_name: 'Николай Сергеевич Мячиков'
    mail: 'djin_udachi@den.skv'

smb_shares_config:
  VG:
    comment: "Для работы специальной группе"
    path: "/srv/smb/spec_GR1"
    writable: "yes"
    guest_ok: "no"
    read_list: "'+Специальная_группа' '+Domain Admins'"
    write_list: "'+Специальная_группа' '+Domain Admins'"
    browseable: "yes"
    create_mask: "0770"
    directory_mask: "0770"

  trash:
    comment: "TyT /7OJLHbIU TRASH"
    path: "/srv/smb/trash"
    writable: "yes"
    guest_ok: "no"
    read_list: "'+Domain Users' '+Domain Admins'"
    write_list: "'+Domain Users' '+Domain Admins'"
    browseable: "yes"
    create_mask: "2775"
    directory_mask: "1775"

  IT:
    comment: "Для администраторов"
    path: "/srv/smb/NOTadmins"
    writable: "yes"
    guest_ok: "no"
    read_list: "'+Domain Admins'"
    write_list: "'+Domain Admins'"
    browseable: "no"
    create_mask: "0770"
    directory_mask: "0770"

  Work:
    comment: "Для работы пользователям домена"
    path: "/srv/smb/work"
    writable: "yes"
    guest_ok: "no"
    read_list: "'+Domain Users' '+Domain Admins'"
    write_list: "'+Domain Users' '+Domain Admins'"
    browseable: "yes"
    create_mask: "0770"
    directory_mask: "0770"

# ==| Для роли NFS сервера |== #
spec_nfs_gr1: "Специальная_группа"

nfs_users:
  user3:
    name: "samba_u3"
    password: "1qaz@WSX"
    given_name: 'Колкин Павел Сергеевич'
    mail: 'garaj@den.skv'
  user4:
    name: "samba_u4"
    password: "1qaz@WSX"
    given_name: 'Николай Сергеевич Мячиков'
    mail: 'djin_udachi@den.skv'

nfs_shares:
  root:
    path: "/srv/smb"
  trash:
    path: "/srv/smb/trash"
  NOTadmins:
    path: "/srv/smb/NOTadmins"
  work:
    path: "/srv/smb/work"
  spec_GR1:
    path: "/srv/smb/spec_GR1"
main_nfs_options: "rw,no_subtree_check"
secure_nfs_options: ",sec=krb5:krb5i:krb5p"

# ==| Для роли SQUID прокси |== #
proxy_group: proxy_acc

negotiate_param: "children 20 startup=0 idle=1"
cache_mem: "1024 MB"
cache_dir: "ufs /var/spool/squid 2048 16 256"
max_obj_size: "100 MB"
max_obj_size_mem: "1 MB"
...
