("/sysconfig-base/language" language ("ru_RU") action "list" language ("ru_RU"))
("/step-list" language ("ru_RU") action "list")
("/help/" language ("ru_RU") action "read" topic "sysconfig-base")
("/sysconfig-base/kbd" language ("ru_RU") action "list" language ("ru_RU"))
("/sysconfig-base/kbd" language ("ru_RU") action "read")
("/help/" language ("ru_RU") action "read" topic "sysconfig-base")
("/sysconfig-base/language" language ("ru_RU") action "write" lang ("ru_RU"))
("/sysconfig-base/kbd" language ("ru_RU") action "write" layout "alt_sh_toggle")
("/notes" language ("ru_RU") action "read" name "license")
("/help/" language ("ru_RU") action "read" topic "notes-license")
("/datetime-installer/avail_region" language ("ru_RU") action "list")
("/datetime-installer/avail_zone" language ("ru_RU") action "list")
("/datetime-installer" language ("ru_RU") action "read")
("/help/" language ("ru_RU") action "read" topic "datetime")
("/datetime-installer" language ("ru_RU") action "write" commit #t name "Europe" zone "Europe/Moscow" utc #t ctime "устанавливается автоматически")
("/pkg-groups" language ("ru_RU") action "read" objects "notifi_transfer_select_grp")
("/pkg-groups" language ("ru_RU") action "list" objects "profiles")
("/pkg-groups" language ("ru_RU") action "read" objects "pkg_groups-config")
("/pkg-groups" language ("ru_RU") action "list")
("pkg-groups-init" language ("ru_RU") action "write")
("/pkg-groups" language ("ru_RU") action "list" objects "profiles")
("/pkg-size" language ("ru_RU") action "write" lists "workstation/daily-planner  workstation/libreoffice workstation/scanning workstation/showtime  workstation/smartcard workstation/thunderbird " language ("ru_RU"))
("/help/" language ("ru_RU") action "read" topic "pkg-groups")
("/pkg-size" language ("ru_RU") action "write" lists "workstation/daily-planner  workstation/libreoffice workstation/scanning workstation/smartcard workstation/alterator-web  workstation/thunderbird workstation/showtime " language ("ru_RU"))
("/pkg-size" language ("ru_RU") action "write" lists "workstation/daily-planner  workstation/libreoffice workstation/scanning workstation/smartcard workstation/alterator-web  workstation/thunderbird workstation/yandex-browser workstation/showtime " language ("ru_RU"))
("/pkg-groups" language ("ru_RU") action "read" group workstation/daily-planner)
("/pkg-groups" language ("ru_RU") action "read" group workstation/scanning)
("pkg-groups-cleanup" language ("ru_RU") action "write")
("/evms/control" language ("ru_RU") action "write" control open installer #t)
("/evms/control" language ("ru_RU") action "write" control update)
("/evms/profiles" language ("ru_RU") action "list")
("/evms/profiles/workstation" language ("ru_RU") action size)
("/evms/profiles/workstation" language ("ru_RU") action title)
("/evms/profiles/workstation-btrfs" language ("ru_RU") action size)
("/evms/profiles/workstation-btrfs" language ("ru_RU") action title)
("/evms/profiles/none" language ("ru_RU") action size)
("/evms/profiles/none" language ("ru_RU") action title)
("/evms/storage/disks" language ("ru_RU") action "list")
("/evms/storage/disks/sda" language ("ru_RU") action props props (id size free))
("/evms/profiles" language ("ru_RU") action "list")
("/evms/profiles/workstation" language ("ru_RU") action check)
("/help/" language ("ru_RU") action "read" topic "vm")
("/evms/profiles" language ("ru_RU") action "list")
("/evms/profiles" language ("ru_RU") action "list")
("/evms/profiles/workstation" language ("ru_RU") action check)
("/evms/profiles/workstation" language ("ru_RU") action apply commit #f clearall #f exclude ())
("/evms/control" language ("ru_RU") action "write" control update)
("/evms/tree" language ("ru_RU") action tree)
("/evms/tree" language ("ru_RU") action ops)
("/help/" language ("ru_RU") action "read" topic "vm")
("/evms/tree/Disks/sda/sda2" language ("ru_RU") action ops)
("/evms/tree/Disks/sda/sda1" language ("ru_RU") action ops)
("/evms/tree/Disks/sda/sda1" language ("ru_RU") action task operation op-volume-destroy)
("/evms/tasks/1" language ("ru_RU") action verbose)
("/evms/tasks/1" language ("ru_RU") action objects)
("/evms/tasks/1" language ("ru_RU") action options)
("/evms/tasks/1" language ("ru_RU") action options)
("/evms/tasks/1" language ("ru_RU") action apply verbose #f next-hop #t)
("/evms/control" language ("ru_RU") action "write" control update)
("/evms/tree" language ("ru_RU") action tree)
("/evms/tree" language ("ru_RU") action ops)
("/evms/tree/Disks/sda/sda2" language ("ru_RU") action ops)
("/evms/tree/Disks/sda/sda2" language ("ru_RU") action task operation op-volume-destroy)
("/evms/tasks/2" language ("ru_RU") action verbose)
("/evms/tasks/2" language ("ru_RU") action objects)
("/evms/tasks/2" language ("ru_RU") action options)
("/evms/tasks/2" language ("ru_RU") action options)
("/evms/tasks/2" language ("ru_RU") action apply verbose #f next-hop #t)
("/evms/control" language ("ru_RU") action "write" control update)
("/evms/tree" language ("ru_RU") action tree)
("/evms/tree" language ("ru_RU") action ops)
("/evms/tree/Disks/sda/<unused1>" language ("ru_RU") action ops)
("/evms/tree/Disks/sda/<unused1>" language ("ru_RU") action task operation op-segment-create)
("/evms/tasks/3" language ("ru_RU") action verbose)
("/evms/tasks/3" language ("ru_RU") action objects)
("/evms/tasks/3" language ("ru_RU") action options)
("/evms/tasks/3" language ("ru_RU") action options)
("/evms/tasks/3" language ("ru_RU") action apply verbose #f next-hop #t)
("/evms/tasks/4" language ("ru_RU") action verbose)
("/evms/tasks/4" language ("ru_RU") action objects)
("/evms/tasks/4" language ("ru_RU") action options)
("/evms/tasks/4" language ("ru_RU") action options)
("/evms/tasks/4" language ("ru_RU") action apply verbose #f next-hop #t)
("/evms/tasks/5" language ("ru_RU") action "read")
("/evms/tasks/6" language ("ru_RU") action "read")
("/evms/tasks/7" language ("ru_RU") action "read")
("/evms/tasks/6" language ("ru_RU") action destroy)
("/evms/tasks/7" language ("ru_RU") action destroy)
("/evms/tasks/5" language ("ru_RU") action verbose)
("/evms/tasks/5" language ("ru_RU") action objects)
("/evms/tasks/5" language ("ru_RU") action options)
("/evms/tasks/5" language ("ru_RU") action options)
("/evms/tasks/5" language ("ru_RU") action apply verbose #f next-hop #t)
("/evms/tasks/8" language ("ru_RU") action verbose)
("/evms/tasks/8" language ("ru_RU") action objects)
("/evms/tasks/8" language ("ru_RU") action options)
("/evms/tasks/8" language ("ru_RU") action options)
("/evms/tasks/8" language ("ru_RU") action set-options! mntoptions "relatime")
("/evms/tasks/8" language ("ru_RU") action set-options! mntpoint "/")
("/evms/tasks/8" language ("ru_RU") action apply verbose #f next-hop #t)
("/evms/control" language ("ru_RU") action "write" control update)
("/evms/tree" language ("ru_RU") action tree)
("/evms/tree" language ("ru_RU") action ops)
("/evms/control" language ("ru_RU") action "read" control assigned)
("/evms/control" language ("ru_RU") action "read" control efi)
("/evms/control" language ("ru_RU") action "read" control efi)
("/evms/control" language ("ru_RU") action "read" control any-ptable)
("/evms/control" language ("ru_RU") action "read" control sufficient)
("/evms/control" language ("ru_RU") action "read" control postponed)
("/evms/control" language ("ru_RU") action "read" control pending)
("/evms/control" language ("ru_RU") action "read" control assigned)
("/evms/tree" language ("ru_RU") action tree)
("/evms/control" language ("ru_RU") action "read" control pending)
("/evms/control" language ("ru_RU") action "write" control commit)
("/evms/control" language ("ru_RU") action "write" control update)
("/evms/tree" language ("ru_RU") action tree)
("/evms/tree" language ("ru_RU") action ops)
("/evms/control" language ("ru_RU") action "write" control close)
("pkg-install-init" language ("ru_RU") action "write")
("/pkg-install/slideshow-config" language ("ru_RU") action "read")
("/pkg-install" language ("ru_RU") action "write" lists #f)
("/help/" language ("ru_RU") action "read" topic "pkg-install")
("/preinstall" language ("ru_RU") action "write")
("/help/" language ("ru_RU") action "read" topic "preinstall")
("/grub/devices" language ("ru_RU") action "list")
("/grub/passwd" language ("ru_RU") action "read")
("/help/" language ("ru_RU") action "read" topic "grub")
("/grub" language ("ru_RU") action "write" language ("ru_RU") device "/dev/disk/by-id/ata-QEMU_HARDDISK_QM00001" passwd #f passwd_1 "*" passwd_2 "*")
("/net-eth/avail_ipv" language ("ru_RU") action "list")
("/net-eth/avail_masks" language ("ru_RU") action "list" ipv "4")
("/net-eth/avail_configurations" language ("ru_RU") action "list" ipv "4")
("/net-eth/avail_ifaces" language ("ru_RU") action "list")
("/net-eth" language ("ru_RU") action "read" name "" ipv "4")
("/net-eth/list_current_iface_address" language ("ru_RU") action "list" name "ens3" ipv "4")
("/help/" language ("ru_RU") action "read" topic "net-eth")
("/net-eth" language ("ru_RU") action "write" name "ens3" ipv "4" ipv_enabled #t controlled "NetworkManager" configuration "dhcp" default "" search "" dns "" computer_name "alt-s-p11-1")
("/net-eth" language ("ru_RU") action "write" commit #t)
("/root/generate_password" language ("ru_RU"))
("/help/" language ("ru_RU") action "read" topic "root")
("/root/change_password" language ("ru_RU") language ("ru_RU") passwd_auto "*" passwd_2 "1qaz@WSX" passwd_1 "1qaz@WSX")
("/root/generate_password" language ("ru_RU"))
("/users/generate_password" language ("ru_RU"))
("/users/allow_autologin" language ("ru_RU") action "read")
("/help/" language ("ru_RU") action "read" topic "users")
("/users/create_account" language ("ru_RU") new_name "sadmin" real_name "" allow_su #t auto #f passwd_auto "*" passwd_1 "1qaz@WSX" passwd_2 "1qaz@WSX" autologin #f)
("/luks/have_active_luks_device" language ("ru_RU"))
("/notes" language ("ru_RU") action "read" name "release-notes")
("/help/" language ("ru_RU") action "read" topic "notes-release-notes")
("/help/" language ("ru_RU") action "read" topic "notes-release-notes")
