---
# параметры суперпользователя
ansible_ssh_private_key_file: " ~/.ssh/id_skv_VKR_vpn"
ansible_user: "{{ vault_su_wheel_user }}"
ansible_become_password: "{{ vault_su_password }}"

# Общие параметры домена
ad_workgroup: "den.skv"
ad_realm: "DEN.SKV"
ad_domain: "DEN"
ad_admin_user: "Administrator"
ad_admin_password: "{{ vault_ad_admin_password }}"

# Сеть
network_subnet: "192.168.100.0"
network_netmask: "255.255.255.0"
network_gateway: "192.168.100.1"
dns_forwarder: "77.88.8.8"
...
