---
- name: Перезапуск squid 
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: "Перезапуск squid"
  async: 30
  poll: 3
  loop:
    - squid
  ignore_unreachable: true
...
