---
- name: Остановка конфликтующих служб
  systemd:
    name: "{{ item }}"
    state: stopped
    masked: true
    enabled: false
  loop: "{{ smaba_conflicts }}"
  ignore_errors: true

- name: Обновление кеша пакетов
  apt_rpm:
    update_cache: true

- name: Установка пакетов Samba DC
  apt_rpm:
    name: "{{ samba_ad_pkg }}"
    state: present

- name: Определить основной интерфейс
  set_fact:
    primary_iface_name: >-
      {{
          ansible_interfaces
          | difference(['lo'])
          | select('match', '^(eth|en)[a-z0-9]*')
          | first
      }}

- name: Настройка DNS резолвера дополнительного DC
  template:
    src: resolv.conf_second_dc_before.j2
    dest: "/etc/net/ifaces/{{ primary_iface_name }}/resolv.conf"
  notify:
    - restart network dc2
    - restart interface dc2
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[1]
    - sysvol_replication | bool
    - not "/var/lib/samba/private/sam.ldb" is exists

- meta: flush_handlers

- name: Ждём восстановления связи вторичного сервера
  wait_for_connection:
    timeout: 120
  when:
    - inventory_hostname == groups['domain_controllers'][1]
    - sysvol_replication | bool

- name: Очистка дефолтных конфигов Samba
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ smaba_conflicts_files }}"
  when: 
    - not "/var/lib/samba/private/sam.ldb" is exists

- name: создание каталога для работы Домена
  file:
    path: /var/lib/samba/sysvol
    state: directory
  when: 
    - not "/var/lib/samba/private/sam.ldb" is exists
...
