---
- name: Остановка конфликтующих служб
  systemd:
    name: "{{ item }}"
    state: stopped
    masked: true
    enabled: false
  loop: 
    - smb
    - nmb
    - krb5kdc
    - slapd
    - bind
    - dnsmasq

- name: Обновление кеша пакетов
  apt_rpm:
    update_cache: true

- name: Установка пакетов Samba DC
  apt_rpm:
    name:
      - task-samba-dc
      - alterator-net-domain
      - alterator-datetime
    state: present
    
- name: Очистка дефолтных конфигов Samba
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/samba/smb.conf
    - /var/lib/samba
    - /var/cache/samba

- name: Определить основной интерфейс
  set_fact:
    primary_iface_name: >-
      {{
          ansible_interfaces
          | difference(['lo'])
          | select('match', '^(eth|en)[a-z0-9]*')
          | first
      }}
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Provisioning основного домен-контроллера
  command: >
    samba-tool domain provision --realm={{ ad_realm }} --domain={{ ad_domain }} --server-role=dc --dns-backend="{{ ad_backend }}" --use-rfc2307 --function-level="{{ func_level }}" --adminpass='{{ ad_admin_password }}' --option="dns forwarder={{ dns_forwarder }}" --option="interfaces= lo {{ primary_iface_name }}" --option="bind interfaces only=yes" --option="dns zone scavenging=yes" --option="allow dns updates=secure only"
  args:
    creates: /var/lib/samba/private/sam.ldb
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Запуск samba AD сервер
  systemd:
    name: "{{ item }}"
    state: started
    masked: false
    enabled: true
  loop: 
    - samba
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Очистка Очистка с интервалом обновления 30 дней
  command: >
    samba-tool dns zoneoptions {{ inventory_hostname }} {{ ad_realm }} --aging=1 --refreshinterval={{ dns_refresh }} -U {{ ad_admin_user }}
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Создание обратной - PTR зоны
  command: >
    samba-tool dns zonecreate {{ inventory_hostname }} {{ ptr_zone }} -U {{ ad_admin_user }}
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Добавление записи типа PTR для обратной зоны самого домен контролера
  command: >
    samba-tool dns add  {{ inventory_hostname }} {{ ptr_zone }} {{ ptr_ip_main_dc }} PTR -U {{ inventory_hostname }} -U {{ ad_admin_user }}
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Настройка DNS резолвера основного DC
  template:
    src: resolv.conf_dc_main.j2
    dest: "/etc/net/ifaces/{{ primary_iface_name }}/resolv.conf"
  notify:
    - restart network
    - restart interface
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Определить основной интерфейс вторичного DC
  set_fact:
    primary_iface_name: >-
      {{
          ansible_interfaces
          | difference(['lo'])
          | select('match', '^(eth|en)[a-z0-9]*')
          | first
      }}
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[1]

- name: Присоединение вторичного контроллера домена
  command: >
    samba-tool domain join {{ ad_realm }} DC -U{{ ad_admin_user }}%{{ ad_join_password }} --realm={{ ad_realm }} --option="ad dc functional level={{ func_level }}" --option="dns forwarder={{ dns_forwarder }}" --option='idmap_ldb:use rfc2307 = yes' --option="interfaces= lo {{ primary_iface_name }}" --option="bind interfaces only=yes" --option="dns zone scavenging=yes" --option="allow dns updates=secure only"
  args:
    creates: /var/lib/samba/private/secrets.tdb
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[1]
  
- name: Запуск samba AD сервер
  systemd:
    name: "{{ item }}"
    state: started
    masked: false
    enabled: true
  loop: 
    - samba
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[1]

- name: Добавление записи типа PTR для обратной зоны вторичного домен контролера
  command: >
    samba-tool dns add  {{ inventory_hostname }} {{ ptr_zone }} {{ ptr_ip_second_dc }} PTR -U {{ inventory_hostname }} -U {{ ad_admin_user }}
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[1]

- name: Настройка DNS резолвера дополнительного DC
  template:
    src: resolv.conf_dc_second.j2
    dest: "/etc/net/ifaces/{{ primary_iface_name }}/resolv.conf"
  notify:
    - restart network dc2
    - restart interface dc2
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[1]
...
