---
- name: Настройка krb5.conf для вторичного DC
  template:
    src: krb5.conf.dc_second.j2
    dest: /etc/krb5.conf
    backup: true

- name: Получаем kerberos билет на имя входящего в доменную группу Domain Admins
  shell: printf '%s\n' '{{ ad_admin_password }}' | kinit Administrator
  no_log: true

- name: Присоединение вторичного контроллера домена
  command: >
    samba-tool domain join
    {{ ad_realm }}
    DC
    -U'{{ ad_admin_user }}%{{ ad_admin_password }}'
    --realm={{ ad_realm }}
    --option="dns forwarder={{ dns_forwarder }}"
    --option='idmap_ldb:use rfc2307 = yes'
    --option="interfaces= lo {{ primary_iface_name }}"
    --option="bind interfaces only=yes"
    --option="dns zone scavenging=yes"
    --option="allow dns updates=secure only"
  no_log: true
  args:
    creates: /var/lib/samba/private/secrets.tdb
  
- name: Запуск samba AD сервер
  systemd:
    name: "{{ item }}"
    state: started
    masked: false
    enabled: true
  loop: 
    - samba

- name: Ожидание готовности Samba
  wait_for:
    port: 53
    host: 127.0.0.1
    timeout: 60
    delay: 5

- name: Настройка DNS резолвера дополнительного DC
  template:
    src: resolv.conf_dc_second.j2
    dest: "/etc/net/ifaces/{{ primary_iface_name }}/resolv.conf"
  notify:
    - restart network dc2
    - restart interface dc2

- name: Репликация с первого контроллера домена на второй
  command: >
    samba-tool drs replicate 
    {{ inventory_hostname }}.{{ ad_workgroup }}
    {{ primary_dc }}.{{ ad_workgroup }}
    {{ ldap_search }}
    -U'{{ ad_admin_user }}%{{ ad_admin_password }}'
  no_log: true
...
