---
- name: Включение таймера sysvol-sync
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    masked: false
    daemon_reload: true
  listen: "Enable sysvol-sync timer"
  async: 10
  poll: 0
  loop:
    - sysvol-sync.timer
  ignore_unreachable: true
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]
...
