---
samba_ad_dc: true
ad_backend: 'SAMBA_INTERNAL'
dns_refresh: 720
ptr_zone: "100.168.192.in-addr.arpa"
ptr_ip_main_dc: 12
ptr_ip_second_dc: 13
ldap_search: "dc=den,dc=skv"
sysvol_replication: true
...
