---
- name: Установки RDP-сервера в ОС Альт
  hosts: alt_work_p11
  become: yes
  become_method: su
  become_user: root
  gather_facts: yes

  # vars_prompt:
  #   - name: "su_password"
  #     prompt: "Введите пароль для su (пользователя sadmin)"
  #     private: yes

  roles:
    - xrdp_skv
