---
- name: Обновление кеша пакетов
  apt_rpm:
    update_cache: true

- name: Установка пакетов для стнхронизации
  apt_rpm:
    name:
      - unison
      - rsync
      - openssh-clients
    state: installed
    
- name: Генерация SSH-ключей для репликации sysvol
  openssh_keypair:
    path: "{{ ssh_sysvol_path }}"
    owner: root
    group: root
    mode: '0600'
    type: ed25519
    comment: "rsync SysVol"
    force: no
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Изменение прав на публичный ключ
  file:
    path: ""{{ ssh_sysvol_path }}".pub"
    owner: root
    group: root
    mode: '0640'
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Копирование публичного ключа на вторичный DC
  authorized_key:
    user: root
    key: "{{ lookup('file', '"{{ ssh_sysvol_path }}".pub') }}"
    state: present
    delegate_to: "{{ (groups['domain_controllers'] | list)[1] }}"
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Развертывание конфига Unison
  template:
    src: sync_dc2.prf.j2
    dest: /root/.unison/sync_dc2.prf
    mode: '0600'

- name: Ручной запуск синхронизации rsync
  synchronize:
    src: "{{ synchron_path }}"
    dest: "{{ synchron_path }}"
    rsync_opts:
      - "--rsh="ssh -p 22 -i {{ ssh_sysvol_path }}""
      - "--log-file /var/log/sysvol-sync.log"
      - "--delete-after -f"+ */" -f"- *" {{ synchron_path }}"
    delegate_to: "{{ (groups['domain_controllers'] | list)[1] }}"
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Ручной запуск синхронизации unison
  command: /usr/bin/unison
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Установка systemd timer для синхронизации
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  loop:
    - sysvol-sync.service
    - sysvol-sync.timer
  notify:
    - Enable sysvol-sync timer
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]

- name: Обновление конфигурации systemd
  systemd:
    name: "{{ item }}"
    masked: false
    daemon_reload: true
  loop:
    - sysvol-sync.service
    - sysvol-sync.timer
  when:
    - inventory_hostname == (groups['domain_controllers'] | list)[0]
...
