---
- name: Перезапуск smb
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: "Перезапуск smb"
  async: 10
  poll: 0
  loop:
    - smb
    - avahi-daemon
...
